# Generated by Django 3.2 on 2021-05-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table='Listing',
        ),
    ]
