# Generated by Django 3.2 on 2021-05-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockdays_start', models.DateTimeField(verbose_name='date start')),
                ('blockdays_end', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='blocksday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_day', to='listings.blockday'),
        ),
    ]
