# Generated by Django 3.2 on 2021-05-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210525_0843'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table=None,
        ),
    ]
