# Generated by Django 3.2 on 2021-05-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
